### ISSUE TITLE
integer divide by zero in prometheus/tsdb.(*LeveledCompactor).Plan

### ISSUE THREAD

**Issue by chlunde** [prometheus/tsdb#121]
Hi, I got a crash on an v2.0.0-beta.1 instance running just a few hours, due to a division by zero.

Do you need more info, or should this statement just be guarded by checking if `NumTombstones == 0`?

https://github.com/prometheus/tsdb/blob/e0aca4bee9ae472d1c164c5562eed2a4bf4c700a/compact.go#L173

```
panic: runtime error: integer divide by zero
goroutine 84 [running]:
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*LeveledCompactor).Plan(0xc42049bdd0, 0x7ffc5a300f03, 0x14, 0x0, 0x15da4889200, 0x15ded7d5400, 0x0, 0x0)
/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/compact.go:173 +0x621
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*DB).compact(0xc4200e82a0, 0xc420011100, 0x0, 0x0)
/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:406 +0x2c5
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*DB).run(0xc4200e82a0)
/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:281 +0x3c6
created by github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.Open
/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:250 +0x488
```

**Comment by chlunde** [comment]
Just fixed by #120
