### ISSUE TITLE
Panic in indexreader

### ISSUE THREAD

**Issue by grobie** [prometheus/tsdb#164]
Prometheus 2.0.0-beta.5 + HTTP accept patch + #158

```
2017-10-05_16:45:48.02684 unexpected fault address 0x7f86171002e4
2017-10-05_16:45:48.02684 fatal error: fault
2017-10-05_16:45:48.03232 [signal SIGSEGV: segmentation violation code=0x1 addr=0x7f86171002e4 pc=0x1593038]
2017-10-05_16:45:48.03233 
2017-10-05_16:45:48.03234 goroutine 144110 [running]:
2017-10-05_16:45:48.03234 runtime.throw(0x1babb8f, 0x5)
2017-10-05_16:45:48.03234       /usr/lib/go/src/runtime/panic.go:605 +0x95 fp=0xcb19506358 sp=0xcb19506338 pc=0x42bc55
2017-10-05_16:45:48.03235 runtime.sigpanic()
2017-10-05_16:45:48.03236       /usr/lib/go/src/runtime/signal_unix.go:374 +0x227 fp=0xcb195063a8 sp=0xcb19506358 pc=0x4426c7
2017-10-05_16:45:48.03236 encoding/binary.binary.bigEndian.Uint32(...)
2017-10-05_16:45:48.03237       /usr/lib/go/src/encoding/binary/binary.go:112
2017-10-05_16:45:48.03237 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*decbuf).be32(...)
2017-10-05_16:45:48.03237       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/encoding_helpers.go:141
2017-10-05_16:45:48.03238 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*decbuf).be32int(...)
2017-10-05_16:45:48.03238       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/encoding_helpers.go:77
2017-10-05_16:45:48.03239 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*indexReader).Postings(0xc9e9ea42a0, 0x1bafb0e, 0x8, 0xc62b29a2eb, 0x20, 0xcb195066f0, 0x4d29aa, 0xc94b690000, 0x1827500)
2017-10-05_16:45:48.03240       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/index.go:860 +0x6c8 fp=0xcb19506598 sp=0xcb195063a8 pc=0x1593038
2017-10-05_16:45:48.03240 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*postingsReader).selectSingle(0xcb19506868, 0x28919e0, 0xca1370d5a0, 0x0, 0xcb19506748)
2017-10-05_16:45:48.03241       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:244 +0x94 fp=0xcb195066f8 sp=0xcb19506598 pc=0x1596df4
2017-10-05_16:45:48.03241 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*postingsReader).Select(0xcb19506868, 0xc534323900, 0x1, 0x1, 0x6, 0x7254c2, 0xc4203c6e00, 0x7f9a415ba1e8, 0xc693650a00)
2017-10-05_16:45:48.03242       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:202 +0x130 fp=0xcb195067e0 sp=0xcb195066f8 pc=0x15966c0
2017-10-05_16:45:48.03243 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*blockQuerier).Select(0xc8496f13c0, 0xc534323900, 0x1, 0x1, 0xca1370d5a0, 0x20)
2017-10-05_16:45:48.03244       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:135 +0x92 fp=0xcb19506888 sp=0xcb195067e0 pc=0x1595e62
2017-10-05_16:45:48.03245 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*querier).sel(0xca1370d480, 0xc8496f1380, 0x1, 0x4, 0xc534323900, 0x1, 0x1, 0x4436d7, 0x30)
2017-10-05_16:45:48.03247       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:94 +0x1d3 fp=0xcb195068f8 sp=0xcb19506888 pc=0x15959c3
2017-10-05_16:45:48.03247 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*querier).sel(0xca1370d480, 0xc8496f1380, 0x2, 0x4, 0xc534323900, 0x1, 0x1, 0x7f9a1cbc35f8, 0x0)
2017-10-05_16:45:48.03249       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:97 +0xac fp=0xcb19506968 sp=0xcb195068f8 pc=0x159589c
2017-10-05_16:45:48.03252 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*querier).sel(0xca1370d480, 0xc8496f1380, 0x4, 0x4, 0xc534323900, 0x1, 0x1, 0x16700000001, 0xca1370d5a0)
2017-10-05_16:45:48.03252       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:97 +0xac fp=0xcb195069d8 sp=0xcb19506968 pc=0x159589c
2017-10-05_16:45:48.03253 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*querier).Select(0xca1370d480, 0xc534323900, 0x1, 0x1, 0x0, 0x1)
2017-10-05_16:45:48.03254       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:85 +0x64 fp=0xcb19506a30 sp=0xcb195069d8 pc=0x15957c4
2017-10-05_16:45:48.03255 github.com/prometheus/prometheus/storage/tsdb.querier.Select(0x28a17a0, 0xca1370d480, 0xc9ee75e3b8, 0x1, 0x1, 0x101, 0xca1370d560)
2017-10-05_16:45:48.03256       /home/grobie/code/go/src/github.com/prometheus/prometheus/storage/tsdb/tsdb.go:166 +0x1c7 fp=0xcb19506ae0 sp=0xcb19506a30 pc=0x15aa907
2017-10-05_16:45:48.03257 github.com/prometheus/prometheus/storage/tsdb.(*querier).Select(0xc5343238f0, 0xc9ee75e3b8, 0x1, 0x1, 0x0, 0x2)
2017-10-05_16:45:48.03258       <autogenerated>:1 +0x63 fp=0xcb19506b28 sp=0xcb19506ae0 pc=0x15abdc3
2017-10-05_16:45:48.03259 github.com/prometheus/prometheus/storage.(*mergeQuerier).Select(0xc693650b00, 0xc9ee75e3b8, 0x1, 0x1, 0xc75f46d7a0, 0xc736699d40)
2017-10-05_16:45:48.03260       /home/grobie/code/go/src/github.com/prometheus/prometheus/storage/fanout.go:183 +0x105 fp=0xcb19506bd0 sp=0xcb19506b28 pc=0x155ad15
2017-10-05_16:45:48.03262 github.com/prometheus/prometheus/promql.(*Engine).populateIterators.func2(0x2885da0, 0xc75f46d7a0, 0x0)
2017-10-05_16:45:48.03263       /home/grobie/code/go/src/github.com/prometheus/prometheus/promql/engine.go:530 +0x579 fp=0xcb19506cc8 sp=0xcb19506bd0 pc=0x15d33c9
2017-10-05_16:45:48.03264 github.com/prometheus/prometheus/promql.inspector.Visit(0xca8a432ed0, 0x2885da0, 0xc75f46d7a0, 0x0, 0xcb19506db8)
2017-10-05_16:45:48.03264       /home/grobie/code/go/src/github.com/prometheus/prometheus/promql/ast.go:306 +0x3a fp=0xcb19506cf0 sp=0xcb19506cc8 pc=0x15ad04a
2017-10-05_16:45:48.03266 github.com/prometheus/prometheus/promql.Walk(0x288d120, 0xca8a432ed0, 0x2885da0, 0xc75f46d7a0)
2017-10-05_16:45:48.03267       /home/grobie/code/go/src/github.com/prometheus/prometheus/promql/ast.go:255 +0x58 fp=0xcb19506d78 sp=0xcb19506cf0 pc=0x15ac6d8
2017-10-05_16:45:48.03268 github.com/prometheus/prometheus/promql.Walk(0x288d120, 0xca8a432ed0, 0x288d0a0, 0xca1370d540)
2017-10-05_16:45:48.03269       /home/grobie/code/go/src/github.com/prometheus/prometheus/promql/ast.go:275 +0x1a8 fp=0xcb19506e00 sp=0xcb19506d78 pc=0x15ac828
2017-10-05_16:45:48.03269 github.com/prometheus/prometheus/promql.Walk(0x288d120, 0xca8a432ed0, 0x2885d20, 0xc693650a00)
2017-10-05_16:45:48.03270       /home/grobie/code/go/src/github.com/prometheus/prometheus/promql/ast.go:285 +0x5df fp=0xcb19506e88 sp=0xcb19506e00 pc=0x15acc5f
2017-10-05_16:45:48.03272 github.com/prometheus/prometheus/promql.Walk(0x288d120, 0xca8a432ed0, 0x2885c60, 0xca2fc9e1e0)
2017-10-05_16:45:48.03272       /home/grobie/code/go/src/github.com/prometheus/prometheus/promql/ast.go:278 +0x47c fp=0xcb19506f10 sp=0xcb19506e88 pc=0x15acafc
2017-10-05_16:45:48.03274 github.com/prometheus/prometheus/promql.Walk(0x288d120, 0xca8a432ed0, 0x2885ce0, 0xca0cd5ad80)
2017-10-05_16:45:48.03274       /home/grobie/code/go/src/github.com/prometheus/prometheus/promql/ast.go:281 +0x7d9 fp=0xcb19506f98 sp=0xcb19506f10 pc=0x15ace59
2017-10-05_16:45:48.03275 github.com/prometheus/prometheus/promql.Walk(0x288d120, 0xca8a432ed0, 0x288d0a0, 0xca1370d500)
2017-10-05_16:45:48.03276       /home/grobie/code/go/src/github.com/prometheus/prometheus/promql/ast.go:275 +0x1a8 fp=0xcb19507020 sp=0xcb19506f98 pc=0x15ac828
2017-10-05_16:45:48.03277 github.com/prometheus/prometheus/promql.Walk(0x288d120, 0xca8a432ed0, 0x2885d20, 0xc693650a40)
2017-10-05_16:45:48.03278       /home/grobie/code/go/src/github.com/prometheus/prometheus/promql/ast.go:285 +0x5df fp=0xcb195070a8 sp=0xcb19507020 pc=0x15acc5f
2017-10-05_16:45:48.03280 github.com/prometheus/prometheus/promql.Walk(0x288d120, 0xca8a432ed0, 0x2885ce0, 0xca0cd5ae80)
2017-10-05_16:45:48.03280       /home/grobie/code/go/src/github.com/prometheus/prometheus/promql/ast.go:281 +0x7d9 fp=0xcb19507130 sp=0xcb195070a8 pc=0x15ace59
2017-10-05_16:45:48.03281 github.com/prometheus/prometheus/promql.Inspect(0x2885ce0, 0xca0cd5ae80, 0xca8a432ed0)
2017-10-05_16:45:48.03282       /home/grobie/code/go/src/github.com/prometheus/prometheus/promql/ast.go:316 +0x4b fp=0xcb19507160 sp=0xcb19507130 pc=0x15ad0eb
2017-10-05_16:45:48.03283 github.com/prometheus/prometheus/promql.(*Engine).populateIterators(0xc420283e60, 0x7f9a4121c000, 0xca6776d5c0, 0xca2fc9e280, 0x411bbc, 0xc4200945a0, 0xcb195072b8, 0x43c81c)
2017-10-05_16:45:48.03284       /home/grobie/code/go/src/github.com/prometheus/prometheus/promql/engine.go:515 +0x3e6 fp=0xcb19507268 sp=0xcb19507160 pc=0x15b0746
2017-10-05_16:45:48.03285 github.com/prometheus/prometheus/promql.(*Engine).execEvalStmt(0xc420283e60, 0x7f9a4121c000, 0xca6776d5c0, 0xca0cd5aec0, 0xca2fc9e280, 0x0, 0x0, 0x0, 0x0)
2017-10-05_16:45:48.03287       /home/grobie/code/go/src/github.com/prometheus/prometheus/promql/engine.go:361 +0xf5 fp=0xcb19507610 sp=0xcb19507268 pc=0x15aec15
2017-10-05_16:45:48.03288 github.com/prometheus/prometheus/promql.(*Engine).exec(0xc420283e60, 0x7f9a4121c000, 0xca6776d5c0, 0xca0cd5aec0, 0x0, 0x0, 0x0, 0x0)
2017-10-05_16:45:48.03289       /home/grobie/code/go/src/github.com/prometheus/prometheus/promql/engine.go:341 +0x317 fp=0xcb19507680 sp=0xcb19507610 pc=0x15ae8e7
2017-10-05_16:45:48.03291 github.com/prometheus/prometheus/promql.(*query).Exec(0xca0cd5aec0, 0x7f9a415738f8, 0xc4207dd240, 0xbe6db64da40a2e05)
2017-10-05_16:45:48.03292       /home/grobie/code/go/src/github.com/prometheus/prometheus/promql/engine.go:179 +0x94 fp=0xcb19507720 sp=0xcb19507680 pc=0x15ad7a4
2017-10-05_16:45:48.03293 github.com/prometheus/prometheus/rules.(*AlertingRule).Eval(0xc560812180, 0x7f9a415738f8, 0xc4207dd240, 0xbe6db64da40a2e05, 0xe4077419b054, 0x296bd00, 0xc420283e60, 0xc420210a00, 0x0, 0x0, ...)
2017-10-05_16:45:48.03295       /home/grobie/code/go/src/github.com/prometheus/prometheus/rules/alerting.go:164 +0x133 fp=0xcb19507a40 sp=0xcb19507720 pc=0x15f7f13
2017-10-05_16:45:48.03296 github.com/prometheus/prometheus/rules.(*Group).Eval.func1(0x1bafb36, 0x8, 0xc560812200, 0xbe6db64da40a2e05, 0xe4077419b054, 0x296bd00, 0x6, 0x28a0f60, 0xc560812180)
2017-10-05_16:45:48.03297       /home/grobie/code/go/src/github.com/prometheus/prometheus/rules/manager.go:307 +0x194 fp=0xcb19507d60 sp=0xcb19507a40 pc=0x15ffe94
2017-10-05_16:45:48.03298 github.com/prometheus/prometheus/rules.(*Group).Eval(0xc560812200, 0xbe6db64da40a2e05, 0xe4077419b054, 0x296bd00)
2017-10-05_16:45:48.03299       /home/grobie/code/go/src/github.com/prometheus/prometheus/rules/manager.go:375 +0xbf fp=0xcb19507de0 sp=0xcb19507d60 pc=0x15fbcef
2017-10-05_16:45:48.03300 github.com/prometheus/prometheus/rules.(*Group).run.func1()
2017-10-05_16:45:48.03301       /home/grobie/code/go/src/github.com/prometheus/prometheus/rules/manager.go:182 +0x81 fp=0xcb19507e30 sp=0xcb19507de0 pc=0x15ffb21
2017-10-05_16:45:48.03302 github.com/prometheus/prometheus/rules.(*Group).run(0xc560812200)
2017-10-05_16:45:48.03302       /home/grobie/code/go/src/github.com/prometheus/prometheus/rules/manager.go:207 +0x23c fp=0xcb19507fb0 sp=0xcb19507e30 pc=0x15fafbc
2017-10-05_16:45:48.03303 github.com/prometheus/prometheus/rules.(*Manager).ApplyConfig.func1.1(0xc4207dd280, 0xc560812200)
2017-10-05_16:45:48.03304       /home/grobie/code/go/src/github.com/prometheus/prometheus/rules/manager.go:510 +0x46 fp=0xcb19507fd0 sp=0xcb19507fb0 pc=0x1601c66
2017-10-05_16:45:48.03305 runtime.goexit()
2017-10-05_16:45:48.03305       /usr/lib/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xcb19507fd8 sp=0xcb19507fd0 pc=0x45ca71
2017-10-05_16:45:48.03306 created by github.com/prometheus/prometheus/rules.(*Manager).ApplyConfig.func1
2017-10-05_16:45:48.03306       /home/grobie/code/go/src/github.com/prometheus/prometheus/rules/manager.go:505 +0x56
```

**Comment by fabxc** [comment]
This should be fixed. Blocks now block on closing until all readers have terminated.
