### ISSUE TITLE
Panic on querying in head block

### ISSUE THREAD

**Issue by fabxc** [prometheus/tsdb#20]
```ERRO[0124] http: panic serving [::1]:54974: runtime error: index out of range
goroutine 330766 [running]:
net/http.(*conn).serve.func1(0xc42a4dc000)
       	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1721 +0xd0
panic(0x24d7fa0, 0x3346720)
       	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
github.com/prometheus/prometheus/vendor/github.com/fabxc/tsdb.(*headBlock).Querier.func1.1(0x74, 0x66, 0x1011300)
       	/Users/fabxc/repos/src/github.com/prometheus/prometheus/vendor/github.com/fabxc/tsdb/head.go:222 +0xb6
sort.medianOfThree_func(0xc432c9ac48, 0xc4331160c0, 0x74, 0x66, 0x58)
       	/usr/local/Cellar/go/1.8/libexec/src/sort/zfuncversion.go:53 +0x3e
sort.doPivot_func(0xc432c9ac48, 0xc4331160c0, 0x0, 0x75, 0x3c01770, 0x0)
       	/usr/local/Cellar/go/1.8/libexec/src/sort/zfuncversion.go:78 +0x5f0
sort.quickSort_func(0xc432c9ac48, 0xc4331160c0, 0x0, 0x75, 0xe)
       	/usr/local/Cellar/go/1.8/libexec/src/sort/zfuncversion.go:143 +0x80
sort.Slice(0x23c81c0, 0xc4331160a0, 0xc432c9ac48)
       	/usr/local/Cellar/go/1.8/libexec/src/sort/sort.go:251 +0xe3
github.com/prometheus/prometheus/vendor/github.com/fabxc/tsdb.(*headBlock).Querier.func1(0x32ad7a0, 0xc433116080, 0x1, 0x32ad7a0)
       	/Users/fabxc/repos/src/github.com/prometheus/prometheus/vendor/github.com/fabxc/tsdb/head.go:223 +0x23e
github.com/prometheus/prometheus/vendor/github.com/fabxc/tsdb.(*blockQuerier).Select(0xc42c2e0bc0, 0xc42c2ea690, 0x1, 0x1, 0xc42c2e1040, 0xc42c2e9bc0)
```

This occasionally happens after a fair amount of spam-querying.

**Comment by Gouthamve** [comment]
This issue needs the commit hash also. Without it, it is pretty hard to fix or even know if this is fixed.

**Comment by Gouthamve** [comment]
Closing as stale. This is not seen in newer versions.
