### ISSUE TITLE
segfault panic in head.go

### ISSUE THREAD

**Issue by beorn7** [prometheus/tsdb#214]
Happening in Prometheus 2.0.0.

Here are the logs, including the one from the restarted server, where a WAL corruption is detected. I assume that's normal after a hard crash, just adding it for completeness.

```
2017-11-26_17:00:47.90248 panic: runtime error: invalid memory address or nil pointer dereference
2017-11-26_17:00:47.90253 [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x159134a]
2017-11-26_17:00:47.90255 
2017-11-26_17:00:47.90255 goroutine 40254909 [running]:
2017-11-26_17:00:47.90256 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*headChunkReader).Chunk(0xc50daf3e00, 0x8ce9f000168, 0x28a0f40, 0xc5b4065200, 0x0, 0x0)
2017-11-26_17:00:47.90257       /go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/head.go:775 +0x8a
2017-11-26_17:00:47.90257 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*populatedChunkSeries).Next(0xc50e6ae000, 0xc4c3c464e0)
2017-11-26_17:00:47.90258       /go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:533 +0x12a
2017-11-26_17:00:47.90258 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*blockSeriesSet).Next(0xc57e27bc40, 0xc5b4064e01)
2017-11-26_17:00:47.90259       /go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:564 +0x48
2017-11-26_17:00:47.90260 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*mergedSeriesSet).Next(0xc57e27bc80, 0xc5b4064901)
2017-11-26_17:00:47.90262       /go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:416 +0x245
2017-11-26_17:00:47.90263 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*mergedSeriesSet).Next(0xc6c2d6c000, 0xc56311fe01)
2017-11-26_17:00:47.90264       /go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:416 +0x245
2017-11-26_17:00:47.90264 github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*mergedSeriesSet).Next(0xc6c2d6c0c0, 0xc5b4802cb8)
2017-11-26_17:00:47.90265       /go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/querier.go:416 +0x245
2017-11-26_17:00:47.90265 github.com/prometheus/prometheus/storage/tsdb.seriesSet.Next(0x2893c80, 0xc6c2d6c0c0, 0xc5efcd1120)
2017-11-26_17:00:47.90265       /go/src/github.com/prometheus/prometheus/storage/tsdb/tsdb.go:208 +0x31
2017-11-26_17:00:47.90266 github.com/prometheus/prometheus/storage/tsdb.(*seriesSet).Next(0xc5ca9b6210, 0x2890540)
2017-11-26_17:00:47.90266       <autogenerated>:1 +0x45
2017-11-26_17:00:47.90267 github.com/prometheus/prometheus/promql.expandSeriesSet(0x289b2c0, 0xc5ca9b6210, 0x1, 0x1, 0x289b2c0, 0xc5ca9b6210, 0x20)
2017-11-26_17:00:47.90267       /go/src/github.com/prometheus/prometheus/promql/engine.go:546 +0x6a
2017-11-26_17:00:47.90268 github.com/prometheus/prometheus/promql.(*Engine).populateIterators.func2(0x2881f00, 0xc52254e420, 0x0)
2017-11-26_17:00:47.90268       /go/src/github.com/prometheus/prometheus/promql/engine.go:518 +0xf2
2017-11-26_17:00:47.90268 github.com/prometheus/prometheus/promql.inspector.Visit(0xc7c31e8780, 0x2881f00, 0xc52254e420, 0x2889100, 0xc7c31e8780)
2017-11-26_17:00:47.90269       /go/src/github.com/prometheus/prometheus/promql/ast.go:305 +0x3a
2017-11-26_17:00:47.90270 github.com/prometheus/prometheus/promql.Walk(0x2889100, 0xc7c31e8780, 0x2881f00, 0xc52254e420)
2017-11-26_17:00:47.90270       /go/src/github.com/prometheus/prometheus/promql/ast.go:254 +0x58
2017-11-26_17:00:47.90271 github.com/prometheus/prometheus/promql.Walk(0x2889100, 0xc7c31e8780, 0x2881c40, 0xc4bec25d60)
2017-11-26_17:00:47.90271       /go/src/github.com/prometheus/prometheus/promql/ast.go:277 +0x47c
2017-11-26_17:00:47.90272 github.com/prometheus/prometheus/promql.Walk(0x2889100, 0xc7c31e8780, 0x2881cc0, 0xc45747f340)
2017-11-26_17:00:47.90272       /go/src/github.com/prometheus/prometheus/promql/ast.go:281 +0x832
2017-11-26_17:00:47.90273 github.com/prometheus/prometheus/promql.Walk(0x2889100, 0xc7c31e8780, 0x2881e00, 0xc755db9840)
2017-11-26_17:00:47.90273       /go/src/github.com/prometheus/prometheus/promql/ast.go:287 +0x6dc
2017-11-26_17:00:47.90273 github.com/prometheus/prometheus/promql.Walk(0x2889100, 0xc7c31e8780, 0x2881cc0, 0xc45747f440)
2017-11-26_17:00:47.90274       /go/src/github.com/prometheus/prometheus/promql/ast.go:280 +0x7d9
2017-11-26_17:00:47.90274 github.com/prometheus/prometheus/promql.Inspect(0x2881cc0, 0xc45747f440, 0xc7c31e8780)
2017-11-26_17:00:47.90275       /go/src/github.com/prometheus/prometheus/promql/ast.go:315 +0x4b
2017-11-26_17:00:47.90276 github.com/prometheus/prometheus/promql.(*Engine).populateIterators(0xc42031f1a0, 0x289cbc0, 0xc52254e540, 0xc4bec25e50, 0x411bcc, 0xc42015a660, 0xc5b48032b8, 0x43c8ac)
2017-11-26_17:00:47.90276       /go/src/github.com/prometheus/prometheus/promql/engine.go:515 +0x409
2017-11-26_17:00:47.90277 github.com/prometheus/prometheus/promql.(*Engine).execEvalStmt(0xc42031f1a0, 0x289cbc0, 0xc52254e540, 0xc45747f480, 0xc4bec25e50, 0x0, 0x0, 0x0, 0x0)
2017-11-26_17:00:47.90277       /go/src/github.com/prometheus/prometheus/promql/engine.go:361 +0xf5
2017-11-26_17:00:47.90278 github.com/prometheus/prometheus/promql.(*Engine).exec(0xc42031f1a0, 0x289cbc0, 0xc52254e540, 0xc45747f480, 0x0, 0x0, 0x0, 0x0)
2017-11-26_17:00:47.90278       /go/src/github.com/prometheus/prometheus/promql/engine.go:341 +0x317
2017-11-26_17:00:47.90279 github.com/prometheus/prometheus/promql.(*query).Exec(0xc45747f480, 0x289cb40, 0xc42036d080, 0xbe7edaacf31c02b9)
2017-11-26_17:00:47.90281       /go/src/github.com/prometheus/prometheus/promql/engine.go:179 +0xb8
2017-11-26_17:00:47.90282 github.com/prometheus/prometheus/rules.(*AlertingRule).Eval(0xc5ef22bc80, 0x289cb40, 0xc42036d080, 0xbe7edaacf31c02b9, 0x31b404c64f6c1, 0x2967e40, 0xc42031f1a0, 0xc420370b80, 0x0, 0x0, ...)
2017-11-26_17:00:47.90282       /go/src/github.com/prometheus/prometheus/rules/alerting.go:163 +0x133
2017-11-26_17:00:47.90283 github.com/prometheus/prometheus/rules.(*Group).Eval.func1(0x1bb1720, 0x8, 0xc48740ea80, 0xbe7edaacf31c02b9, 0x31b404c64f6c1, 0x2967e40, 0x2a, 0x289ce80, 0xc5ef22bc80)
2017-11-26_17:00:47.90283       /go/src/github.com/prometheus/prometheus/rules/manager.go:307 +0x194
2017-11-26_17:00:47.90284 github.com/prometheus/prometheus/rules.(*Group).Eval(0xc48740ea80, 0xbe7edaacf31c02b9, 0x31b404c64f6c1, 0x2967e40)
2017-11-26_17:00:47.90284       /go/src/github.com/prometheus/prometheus/rules/manager.go:375 +0xbf
2017-11-26_17:00:47.90285 github.com/prometheus/prometheus/rules.(*Group).run.func1()
2017-11-26_17:00:47.90286       /go/src/github.com/prometheus/prometheus/rules/manager.go:182 +0x81
2017-11-26_17:00:47.90286 github.com/prometheus/prometheus/rules.(*Group).run(0xc48740ea80)
2017-11-26_17:00:47.90287       /go/src/github.com/prometheus/prometheus/rules/manager.go:207 +0x23c
2017-11-26_17:00:47.90288 github.com/prometheus/prometheus/rules.(*Manager).ApplyConfig.func1.1(0xc42036d140, 0xc48740ea80)
2017-11-26_17:00:47.90289       /go/src/github.com/prometheus/prometheus/rules/manager.go:511 +0x46
2017-11-26_17:00:47.90289 created by github.com/prometheus/prometheus/rules.(*Manager).ApplyConfig.func1
2017-11-26_17:00:47.90290       /go/src/github.com/prometheus/prometheus/rules/manager.go:506 +0x56
2017-11-26_17:00:49.37437 level=info ts=2017-11-26T17:00:49.374245725Z caller=main.go:215 msg="Starting Prometheus" version="(version=2.0.0, branch=HEAD, revision=0a74f98628a0463dddc90528220c94de5032d1a0)"  
2017-11-26_17:00:49.37440 level=info ts=2017-11-26T17:00:49.374344085Z caller=main.go:216 build_context="(go=go1.9.2, user=root@615b82cb36b6, date=20171108-07:11:59)"  
2017-11-26_17:00:49.37441 level=info ts=2017-11-26T17:00:49.37437057Z caller=main.go:217 host_details="(Linux 3.16.7-ckt11+soundcloud #1 SMP Tue Jul 28 12:47:15 UTC 2015 x86_64 <elided> (none))"  
2017-11-26_17:00:49.37852 level=info ts=2017-11-26T17:00:49.378340687Z caller=main.go:314 msg="Starting TSDB"  
2017-11-26_17:00:49.37855 level=info ts=2017-11-26T17:00:49.378422132Z caller=web.go:380 component=web msg="Start listening for connections" address=0.0.0.0:9090  
2017-11-26_17:00:49.37857 level=info ts=2017-11-26T17:00:49.378414632Z caller=targetmanager.go:71 component="target manager" msg="Starting target manager..."  
2017-11-26_17:02:01.68930 level=error ts=2017-11-26T17:02:01.689172447Z caller=wal.go:275 component=tsdb msg="WAL corruption detected; truncating" err="unexpected CRC32 checksum 6e034c4c, want 0" file=/srv/prometheus/storage/wal/003474 pos=236125566
```

**Comment by Gouthamve** [comment]
This looks like the following:

1. The index reader gets the chunks for a series.
2. GC kicks in a deletes some of the chunks.
3. The chunks are accessed via reference and [nil is returned](https://github.com/prometheus/tsdb/blob/master/head.go#L781).
4. We don't check if the chunk is nil and panic.

I think the simplest solution here is to check if the chunk returned is nil, and if yes, move on to the next one. But not sure if the cause is actually the one mentioned above. @fabxc

**Comment by fabxc** [comment]
If that's the cause, adding an extra check seems right.
