### ISSUE TITLE
tsdb unit test failure

### ISSUE THREAD

**Issue by mrsiano** [prometheus/tsdb#413]
I wanted to run some benchmark for wal.go, and also include a unit test for it.

I've started with something quite simple
https://github.com/mrsiano/prometheus/blob/9862a8c5fd34ae1f148e36af67f0f6f855b5ed8c/vendor/github.com/prometheus/tsdb/wal_test.go

and it's failed due to
--- FAIL: TestSegementLogDeletes (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x112ba42]

goroutine 19 [running]:
testing.tRunner.func1(0xc4201441e0)
	/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:711 +0x2d2
panic(0x13828a0, 0x15eb790)
	/usr/local/Cellar/go/1.9.3/libexec/src/runtime/panic.go:491 +0x283
hash/crc32.simpleUpdate(0x0, 0x0, 0xc4209ac000, 0x6, 0x6, 0xc420998000)
	/usr/local/Cellar/go/1.9.3/libexec/src/hash/crc32/crc32_generic.go:47 +0x42
hash/crc32.(*digest).Write(0xc420140000, 0xc4209ac000, 0x6, 0x6, 0xc420040db8, 0x1012fb8, 0x10)
	/usr/local/Cellar/go/1.9.3/libexec/src/hash/crc32/crc32.go:186 +0xd3
io.(*multiWriter).Write(0xc4209aa000, 0xc4209ac000, 0x6, 0x6, 0xc4209aa000, 0x800000, 0x20c0008)
	/usr/local/Cellar/go/1.9.3/libexec/src/io/multi.go:60 +0x8f
github.com/mrsiano/prometheus/vendor/github.com/prometheus/tsdb.(*SegmentWAL).writeTo(0x15f14c0, 0x15bb1a0, 0xc4209aa000, 0x20c0000, 0xc420140000, 0x1020104, 0xc420148000, 0xa, 0x10000, 0x131cacb, ...)
	/Users/emarcian/go/src/github.com/mrsiano/prometheus/vendor/github.com/prometheus/tsdb/wal.go:788 +0x16f
github.com/mrsiano/prometheus/vendor/github.com/prometheus/tsdb.(*SegmentWAL).write(0x15f14c0, 0x13f0104, 0xc420148000, 0xa, 0x10000, 0x15b5d01, 0x39)
	/Users/emarcian/go/src/github.com/mrsiano/prometheus/vendor/github.com/prometheus/tsdb/wal.go:768 +0xef
github.com/mrsiano/prometheus/vendor/github.com/prometheus/tsdb.(*SegmentWAL).LogDeletes(0x15f14c0, 0xc420051f78, 0x1, 0x1, 0x0, 0x0)
	/Users/emarcian/go/src/github.com/mrsiano/prometheus/vendor/github.com/prometheus/tsdb/wal.go:504 +0xff
github.com/mrsiano/prometheus/vendor/github.com/prometheus/tsdb.TestSegementLogDeletes(0xc4201441e0)
	/Users/emarcian/go/src/github.com/mrsiano/prometheus/vendor/github.com/prometheus/tsdb/wal_test.go:40 +0xb1
testing.tRunner(0xc4201441e0, 0x13ff4a0)
	/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:789 +0x2de
exit status 2
FAIL	github.com/mrsiano/prometheus/vendor/github.com/prometheus/tsdb

any thoughts ?!

**Comment by krasi-georgiev** [comment]
that is good homework to learn the tsdb internals :stuck_out_tongue_winking_eye: 

the tsdb cli tool has some bench command so you can check it 
https://github.com/prometheus/tsdb/blob/master/cmd/tsdb/main.go#L43

although incomplete and probably outdated here is  a doc start by Goutham and than I also added few notes while learning tsdb.
https://docs.google.com/document/d/1t5eSLlH36oK1Ex3PWwuc4R58kx4PC7Ago90TRR_7nmo
